################################################################################
# Third Reality Smart Watering (ZHA) — HA 2026.1+
#
# Entities (expected):
#  - sensor.basil_humidity            (% soil moisture)
#  - sensor.basil_temperature         (°C, optional)
#  - sensor.basic_battery             (% soil sensor battery)
#  - switch.water_pump
#  - input_number.water_pump_duration (seconds)
#  - input_number.water_pump_interval (days)
#  - sensor.water_pump_battery        (% pump battery)
################################################################################

input_boolean:
  watering_enabled:
    name: Watering enabled
    icon: mdi:water-pump

input_number:
  basil_moisture_low:
    name: Basil moisture LOW threshold
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    initial: 18

  basil_moisture_target:
    name: Basil moisture TARGET
    min: 0
    max: 100
    step: 1
    unit_of_measurement: "%"
    initial: 28

################################################################################
# Script: run pump for X seconds (failsafe built-in)
################################################################################
script:
  water_pump_run_safe:
    alias: Water Pump — Run (safe)
    mode: single
    fields:
      seconds:
        description: "How long to run the pump (seconds)"
        example: 20
    variables:
      secs: >-
        {{ (seconds
            | default(states('input_number.water_pump_duration'))
            | int(20)) }}
      safe_secs: "{{ [secs, 120] | min }}"
    sequence:
      - condition: state
        entity_id: input_boolean.watering_enabled
        state: "on"

      - service: switch.turn_on
        target:
          entity_id: switch.water_pump

      - delay:
          seconds: "{{ safe_secs }}"

      - service: switch.turn_off
        target:
          entity_id: switch.water_pump

################################################################################
# Automations
################################################################################
automation:

  # 1) Interval-based watering (simple scheduler)
  - id: bt_watering_interval_schedule
    alias: Basil — Watering (interval schedule)
    mode: single
    trigger:
      - platform: time
        at: "10:00:00"

    condition:
      - condition: state
        entity_id: input_boolean.watering_enabled
        state: "on"

      - condition: template
        value_template: >-
          {% set last = this.attributes.last_triggered %}
          {% set days = states('input_number.water_pump_interval') | int(1) %}
          {{ last is none or (now() - last).total_seconds() > (days * 86400) }}

    action:
      - service: script.water_pump_run_safe
        data:
          seconds: "{{ states('input_number.water_pump_duration') | int(20) }}"

  # 2) Soil moisture smart watering
  - id: bt_watering_when_soil_low
    alias: Basil — Watering (soil moisture smart trigger)
    mode: single
    trigger:
      - platform: template
        value_template: >-
          {% set m = states('sensor.basil_humidity') | float(-1) %}
          {% set low = states('input_number.basil_moisture_low') | float(0) %}
          {{ m >= 0 and m < low }}
        for: "00:10:00"

    condition:
      - condition: state
        entity_id: input_boolean.watering_enabled
        state: "on"

      - condition: time
        after: "08:00:00"
        before: "21:00:00"

      - condition: template
        value_template: >-
          {% set last = this.attributes.last_triggered %}
          {% set days = states('input_number.water_pump_interval') | int(1) %}
          {{ last is none or (now() - last).total_seconds() > (days * 86400) }}

      - condition: template
        value_template: >-
          {% set m = states('sensor.basil_humidity') | float(-1) %}
          {% set target = states('input_number.basil_moisture_target') | float(0) %}
          {{ m >= 0 and m < target }}

    action:
      - service: logbook.log
        data:
          name: "Watering"
          message: >-
            Soil low ({{ states('sensor.basil_humidity') }}%). Watering for
            {{ states('input_number.water_pump_duration') }}s.

      - service: script.water_pump_run_safe
        data:
          seconds: "{{ states('input_number.water_pump_duration') | int(20) }}"

      - delay: "00:20:00"

      - choose:
          - conditions:
              - condition: template
                value_template: >-
                  {% set m = states('sensor.basil_humidity') | float(-1) %}
                  {% set low = states('input_number.basil_moisture_low') | float(0) %}
                  {{ m >= 0 and m < low }}
            sequence:
              - service: notify.telegram_ebrzsmbrbot
                data:
                  message: >-
                    ⚠️ Basil still reads very dry after watering.
                    Check the water bucket, tubing position, and filter.

  # 3) Pump failsafe
  - id: bt_watering_pump_failsafe_off
    alias: Basil — Pump failsafe (force off after 2 min)
    mode: single
    trigger:
      - platform: state
        entity_id: switch.water_pump
        to: "on"
        for: "00:02:00"
    action:
      - service: switch.turn_off
        target:
          entity_id: switch.water_pump
      - service: notify.telegram_ebrzsmbrbot
        data:
          message: "🛑 Failsafe: water_pump was ON for 2 minutes — turned OFF."

  # 4) Battery alerts (anti-spam)
  - id: bt_basil_soil_sensor_low_battery
    alias: Basil — Soil sensor low battery
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.basic_battery
        below: 15
    condition:
      - condition: template
        value_template: >-
          {% set last = this.attributes.last_triggered %}
          {{ last is none or (now() - last).total_seconds() > 86400 }}
    action:
      - service: notify.telegram_ebrzsmbrbot
        data:
          message: "🔋 Basil soil sensor battery low ({{ states('sensor.basic_battery') }}%)."

  - id: bt_basil_pump_low_battery
    alias: Basil — Water pump low battery
    mode: single
    trigger:
      - platform: numeric_state
        entity_id: sensor.water_pump_battery
        below: 20
    condition:
      - condition: template
        value_template: >-
          {% set last = this.attributes.last_triggered %}
          {{ last is none or (now() - last).total_seconds() > 86400 }}
    action:
      - service: notify.telegram_ebrzsmbrbot
        data:
          message: "🔋 Water pump battery low ({{ states('sensor.water_pump_battery') }}%)."

  # 5) Health check — sensor unavailable
  - id: bt_basil_soil_sensor_unavailable
    alias: Basil — Soil sensor unavailable
    mode: single
    trigger:
      - platform: state
        entity_id: sensor.basil_humidity
        to: "unavailable"
        for: "00:10:00"
    condition:
      - condition: template
        value_template: >-
          {% set last = this.attributes.last_triggered %}
          {{ last is none or (now() - last).total_seconds() > 43200 }}
    action:
      - service: notify.telegram_ebrzsmbrbot
        data:
          message: "⚠️ Basil soil sensor is unavailable for 10+ minutes. Check Zigbee mesh / battery."
